import { DefaultLayout } from "@/layouts/DefaultLayout";
import "./globals.css"; // Đảm bảo Tailwind được import

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DefaultLayout>
        <body>{children}</body>
      </DefaultLayout>
    </html>
  );
}
